tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ebf1ff",
        "inverse-surface": "#263142",
        "tertiary-container": "#191c1e",
        "surface-variant": "#d8e3fa",
        "outline-variant": "#c5c6cd",
        "surface-container": "#e7eeff",
        primary: "#000000",
        "on-secondary-fixed-variant": "#93000d",
        "on-surface": "#111c2c",
        "surface-container-highest": "#d8e3fa",
        outline: "#75777e",
        "secondary-fixed": "#ffdad6",
        "inverse-primary": "#b9c7e4",
        "surface-tint": "#515f78",
        "tertiary-fixed": "#e0e3e6",
        "surface-bright": "#f9f9ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-container": "#e41f25",
        background: "#f9f9ff",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#191c1e",
        "surface-container-low": "#f0f3ff",
        "surface-dim": "#cfdaf1",
        secondary: "#bb0014",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#818487",
        "primary-fixed": "#d6e3ff",
        "surface-container-high": "#dee8ff",
        "primary-fixed-dim": "#b9c7e4",
        "on-secondary-fixed": "#410002",
        "on-primary-fixed-variant": "#39475f",
        "on-secondary": "#ffffff",
        "on-primary-container": "#76849f",
        "primary-container": "#0d1c32",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed-dim": "#c4c7ca",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0d1c32",
        tertiary: "#000000",
        surface: "#f9f9ff",
        "on-surface-variant": "#44474d",
        "secondary-fixed-dim": "#ffb4ab",
        "on-background": "#111c2c",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#44474a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "120px",
        gutter: "24px",
        "margin-desktop": "64px",
        base: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Montserrat"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        button: ["Montserrat"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          {
            lineHeight: "1.3",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "1",
            letterSpacing: "0.08em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
        button: [
          "14px",
          {
            lineHeight: "1",
            letterSpacing: "0.02em",
            fontWeight: "600",
          },
        ],
      },
    },
  },
};
